### ISSUE TITLE
Redesign Add Folder Interface

### ISSUE THREAD

**Issue by ztlee042** [graasp/graasp-builder#1131]
- [x] add avatar selector to name input
- [x] modify how the thumbnail is handled
  - [x] pass data as FormData
  - [x] query-client changes
  - [x] backend changes
- [x] fix styling

![image](https://github.com/graasp/graasp-builder/assets/31677780/843d45f4-4316-42b8-b06e-e634aba171d1)

**Comment by spaenleh** [comment]
Implemented in #1207
