### ISSUE TITLE
A 0 is displayed when removing all tags from Publishing view 

### ISSUE THREAD

**Issue by ReidyT** [graasp/graasp-builder#1209]
![image](https://github.com/graasp/graasp-builder/assets/147397675/37fd30fd-3d1b-4603-91a2-f675b362dca3)

**Comment by pyphilia** [comment]
@ReidyT is it still an issue? you can close if it's not.

**Comment by ReidyT** [comment]
Oh yes thanks for the remider, it is solved when I updated the way to add tags.
