### ISSUE TITLE
searching on name when adding application is not working

### ISSUE THREAD

**Issue by juancarlosfarah** [graasp/graasp-builder#493]
When you add an application as an item and you search, the search is on the URL and not the name of the item.

Should work:

<img width="841" alt="image" src="https://user-images.githubusercontent.com/1707188/200929936-91c96566-f614-41ec-be80-7fc22a719c96.png">

Shouldn't work:

<img width="866" alt="image" src="https://user-images.githubusercontent.com/1707188/200930140-4e289675-49bc-4aab-8c85-518369ba5fb2.png">

**Comment by spaenleh** [comment]
There is a difference in the `Autocomplete` component between the `value` prop and the `inputValue` prop, i think we should have one track the url and the other track the app name (which would be the search string used)
