### ISSUE TITLE
Decrease drag icon in table

### ISSUE THREAD

**Issue by pyphilia** [graasp/graasp-builder#495]
This should have been fixed in graasp-ui, but didn't seem to have been applied in builder.

**Comment by spaenleh** [comment]
@pyphilia Is the current size satisfactory ?
<img width="160" alt="Screenshot 2023-08-04 at 15 19 36" src="https://github.com/graasp/graasp-builder/assets/39373170/6e331339-24d7-433b-9e67-f986083525dd">
