### ISSUE TITLE
Impossible to delete all selected items permanently

### ISSUE THREAD

**Issue by swouf** [graasp/graasp-builder#522]
In the trash, one may want to delete permanently most, if not all, trashed items. Therefore, one would select all items in the table, as shown here:
<img width="1910" alt="Screenshot 2023-01-10 at 13 26 55" src="https://user-images.githubusercontent.com/5767619/211552312-ebd87e0e-fe47-4045-920d-5a50a7acbcc9.png">

But when choosing to delete them permanently, the following error occurs:
<img width="1910" alt="Screenshot 2023-01-10 at 13 08 40" src="https://user-images.githubusercontent.com/5767619/211552429-eceb4af7-2a58-444c-b7f2-f33f8206f40c.png">

I propose automatically selecting only the first 15 items or changing the request to delete all selected items.

**Comment by spaenleh** [comment]
@swouf @pyphilia Can you confirm that we are now splitting the request in chunks and that this error does not happen anymore ?
