### ISSUE TITLE
Report a bug button

### ISSUE THREAD

**Issue by dialexo** [graasp/graasp-builder#542]
We could leverage precise insights into problems by adding a "report a bug" feature. This could be a simple form, and users could type in what they did and what failed. In more advanced scenarios, we could allow them to specify which item / action caused the bug. We could also combine it with some replay capabilities (maybe with Sentry?).

**Comment by spaenleh** [comment]
We could also leverage Sentry's ability to show an alternate ui when an error arrises, don't remember the full name. Also replays are super cool !

**Comment by dialexo** [comment]
> We could also leverage Sentry's ability to show an alternate ui when an error arrises, don't remember the full name. Also replays are super cool !

👍 There's also simply React's `ErrorBoundary` which we should add i think at least in the content region of the UI, such that the user at least gets some feedback
