### ISSUE TITLE
in new item -> app menu, show list of apps instead of URL dropdown

### ISSUE THREAD

**Issue by juancarlosfarah** [graasp/graasp-builder#569]
Currently, to add an app, you have to select it from a URL dropdown.

<img width="889" alt="image" src="https://user-images.githubusercontent.com/1707188/220397638-8b8d5fdf-5d88-4a7f-b0b2-16c7269a5391.png">

Instead, we would like to show this as a grid of icon / name / description, where users can select the app by clicking on it.

There should also be a search box to filter these items.

This element should be factored out to Graasp UI and simply populate itself with the data available in Graasp Builder.

**Comment by juancarlosfarah** [comment]
@pyphilia, @spaenleh, feel free to add any further information.

**Comment by pyphilia** [comment]
Let's also have an "advanced field" to let the user add an custom url.
