### ISSUE TITLE
Pinning an item changes the order of the elements in the folder

### ISSUE THREAD

**Issue by spaenleh** [graasp/graasp-builder#602]
If there was no order defined (by manually re-ordering the items) the action of pinning an item will move it to the bottom of the folder.

This is expected as the item has been updated. But is not desirable.

It would be better to already initialize the `childrenOrder` prop of the folder when creating it. Updating it when new items are added by pushing to the end of the array. This way the order is always set and there is no unexpected "re-ordering" of the items when editing their properties.

Ref graasp/graasp#535

**Comment by spaenleh** [comment]
@pyphilia @dialexo @swouf @juancarlosfarah What do you think of this ?

**Comment by juancarlosfarah** [comment]
Yes. I believe this has been documented in another bug. Like editing an item would change its order. I think order by default should be either (i) set or (ii) be last updated first. I thought (ii) was the default now.

**Comment by spaenleh** [comment]
I think the default now is "updatedAt ascending" so the first element would be the oldest and and the newest (or most recently edited) would be the last.
