### ISSUE TITLE
Reorder item menu actions

### ISSUE THREAD

**Issue by pyphilia** [graasp/graasp-builder#977]
Actions in table

**Comment by LinaYahya** [comment]
Already now in setting page

**Comment by pyphilia** [comment]
I don't think this is done, it's still partly in the responsive PR, and we didn't order item's actions or children's actions.

<img width="364" alt="Screenshot 2024-03-19 at 14 46 38" src="https://github.com/graasp/graasp-builder/assets/11229627/d8424c2d-c9e6-46b6-a1b5-f80e1724018f">
