### ISSUE TITLE
Improve file upload dropzone

### ISSUE THREAD

**Issue by ztlee042** [graasp/graasp-builder#999]
This implementation is used for A/B Testing with users.

This improvement aims to make the drag-and-drop file uploading feature discoverable to users, also improve the ux of drag-and-drop zone.

- [x] #1040

---
https://www.figma.com/file/AMVdgMVt4RRW4j1YSmij5k/Drag-%26-Drop?type=design&node-id=2004%3A158&mode=dev&t=TVmYEMX4APhTJjeR-1

**Comment by pyphilia** [comment]
Is that done? Can we close this? @ztlee042 @spaenleh
